services:
  db:
    image: postgres:17-alpine
    container_name: db
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    hostname: ${REDIS_HOST}
    volumes:
      - ./data/redis_data:/data

  api:
    build: .
    container_name: api
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    entrypoint: [ "sh", "-c", "alembic upgrade head && exec python main.py" ]

  worker:
    build: .
    container_name: worker
    depends_on:
      - db
      - redis
      - api
    entrypoint: [ "sh", "-c", "exec python worker.py" ]
